enum SmithersErrorTypes {
  DB_SECRET_NOT_FOUND = "SMITHERS_DB_SECRET_NOT_FOUND",
  DB_CONNECTION_NOT_FOUND = "SMITHERS_DB_CONNECTION_NOT_FOUND",

  CRAWL_TARGET_UNKNOWN_APP_KEY = "SMITHERS_CRAWL_TARGET_UNKNOWN_APP_KEY",
  CRAWL_TARGET_UPDATE_AT_LEAST_ONE_PROPERTY = "SMITHERS_CRAWL_TARGET_UPDATE_AT_LEAST_ONE_PROPERTY",

  MANGA_UPDATE_UNKNOWN_APP_KEY = "SMITHERS_MANGA_UPDATE_UNKNOWN_APP_KEY",
  MANGA_UPDATE_UPDATE_AT_LEAST_ONE_PROPERTY = "SMITHERS_MANGA_UPDATE_UPDATE_AT_LEAST_ONE_PROPERTY",

  MANGA_CRAWL_TARGET_NOT_FOUND = "SMITHERS_MANGA_CRAWL_TARGET_NOT_FOUND",
  MANGA_CRAWL_TARGET_UNKNOWN_ADAPTER = "SMITHERS_MANGA_CRAWL_TARGET_UNKNOWN_ADAPTER",

  MANGADEX_CURSOR_FAILED_IDENTIFICATION = "SMITHERS_MANGADEX_CURSOR_FAILED_IDENTIFICATION",
  MANGADEX_CURSOR_NO_MORE_CHAPTERS = "SMITHERS_MANGADEX_CURSOR_NO_MORE_CHAPTERS",
  MANGADEX_CURSOR_NO_NEXT = "SMITHERS_MANGADEX_CURSOR_NO_NEXT",

  WEBTOON_CURSOR_UNPARSABLE_CHAPTER = "SMITHERS_WEBTOON_CURSOR_UNPARSABLE_CHAPTER",
  WEBTOON_CURSOR_UNPARSABLE_CHAPTER_LINK = "SMITHERS_WEBTOON_CURSOR_UNPARSABLE_CHAPTER_LINK",
  WEBTOON_CURSOR_NO_TITLE = "SMITHERS_WEBTOON_CURSOR_NO_TITLE",
  WEBTOON_CURSOR_NO_MORE_CHAPTERS = "SMITHERS_WEBTOON_CURSOR_NO_MORE_CHAPTERS"
}

class SmithersError extends Error {
  public isSmithersError = true
  public type: SmithersErrorTypes
  public context: any
  
  constructor(type: SmithersErrorTypes, message: string, context?: any) {
    super(message)
    this.type = type
    this.context = context
  }
}

export {
  SmithersError,
  SmithersErrorTypes
}